// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhRnjJdLmuwtsVmSmyAHtpsF4xTZI_NIU',
    appId: '1:202687364774:web:40856bc5c6d7b05f96be67',
    messagingSenderId: '202687364774',
    projectId: 'convida-ai-database-6baf3',
    authDomain: 'convida-ai-database-6baf3.firebaseapp.com',
    storageBucket: 'convida-ai-database-6baf3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWCU_P8fxrkfC5oGySg5Og8yCE5wdb3-A',
    appId: '1:202687364774:android:10fe6bc8ea1e706796be67',
    messagingSenderId: '202687364774',
    projectId: 'convida-ai-database-6baf3',
    storageBucket: 'convida-ai-database-6baf3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUnW8au5EygpnBKuMbvQmOjVit5R7Wdc4',
    appId: '1:202687364774:ios:82a3ed4fd9e341d096be67',
    messagingSenderId: '202687364774',
    projectId: 'convida-ai-database-6baf3',
    storageBucket: 'convida-ai-database-6baf3.appspot.com',
    androidClientId: '202687364774-m7brie8e8tpkih5ijhu00ars7siv08dq.apps.googleusercontent.com',
    iosClientId: '202687364774-e6k87b2tktkuf59t444k57udcku8hfag.apps.googleusercontent.com',
    iosBundleId: 'cancel',
  );
}
